{"name": "test_login[admin@email.com-admin@123454545]", "status": "broken", "statusDetails": {"message": "TypeError: argument of type 'NoneType' is not iterable", "trace": "self = <tests.test_login_script.TestLoginScenario object at 0x1072f0b90>, email = 'admin@email.com', password = 'admin@123454545'\n\n    @pytest.mark.parametrize(\"email,password\", ExcelUtils.get_excel_data(file_path, \"login_credentials\"))\n    def test_login(self, email, password):\n        login = LoginPage(self.driver)\n        login.login_to_application(email, password)\n    \n        home = HomePage(self.driver)\n    \n        welcome_msg = home.get_welcome_text()\n    \n        print(\"Welcome msg is \" ,welcome_msg)\n    \n>       assert \"Welcome\" in welcome_msg\nE       TypeError: argument of type 'NoneType' is not iterable\n\ntests/test_login_script.py:25: TypeError"}, "steps": [{"name": "Attach Screenshot On Failure/Broken", "status": "broken", "statusDetails": {"message": "TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType\n", "trace": "  File \"/Users/mukeshotwani/PycharmProjects/Framework/tests/conftest.py\", line 41, in pytest_runtest_makereport\n    allure.attach.file(screenshot_path,name=\"Failure Screenshot\",attachment_type=allure.attachment_type.PNG)\n    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/mukeshotwani/PycharmProjects/Framework/.venv/lib/python3.13/site-packages/allure_commons/_allure.py\", line 203, in file\n    plugin_manager.hook.attach_file(source=source, name=name, attachment_type=attachment_type, extension=extension)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/mukeshotwani/PycharmProjects/Framework/.venv/lib/python3.13/site-packages/pluggy/_hooks.py\", line 513, in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n           ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/mukeshotwani/PycharmProjects/Framework/.venv/lib/python3.13/site-packages/pluggy/_manager.py\", line 120, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/mukeshotwani/PycharmProjects/Framework/.venv/lib/python3.13/site-packages/pluggy/_callers.py\", line 139, in _multicall\n    raise exception.with_traceback(exception.__traceback__)\n  File \"/Users/mukeshotwani/PycharmProjects/Framework/.venv/lib/python3.13/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Users/mukeshotwani/PycharmProjects/Framework/.venv/lib/python3.13/site-packages/allure_pytest/listener.py\", line 256, in attach_file\n    self.allure_logger.attach_file(uuid4(), source, name=name, attachment_type=attachment_type, extension=extension)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/mukeshotwani/PycharmProjects/Framework/.venv/lib/python3.13/site-packages/allure_commons/reporter.py\", line 160, in attach_file\n    plugin_manager.hook.report_attached_file(source=source, file_name=file_name)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/mukeshotwani/PycharmProjects/Framework/.venv/lib/python3.13/site-packages/pluggy/_hooks.py\", line 513, in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n           ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/mukeshotwani/PycharmProjects/Framework/.venv/lib/python3.13/site-packages/pluggy/_manager.py\", line 120, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/mukeshotwani/PycharmProjects/Framework/.venv/lib/python3.13/site-packages/pluggy/_callers.py\", line 139, in _multicall\n    raise exception.with_traceback(exception.__traceback__)\n  File \"/Users/mukeshotwani/PycharmProjects/Framework/.venv/lib/python3.13/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Users/mukeshotwani/PycharmProjects/Framework/.venv/lib/python3.13/site-packages/allure_commons/logger.py\", line 39, in report_attached_file\n    shutil.copy2(source, destination)\n    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/shutil.py\", line 468, in copy2\n    copyfile(src, dst, follow_symlinks=follow_symlinks)\n    ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/shutil.py\", line 239, in copyfile\n    if _samefile(src, dst):\n       ~~~~~~~~~^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/shutil.py\", line 216, in _samefile\n    return os.path.samefile(src, dst)\n           ~~~~~~~~~~~~~~~~^^^^^^^^^^\n  File \"<frozen genericpath>\", line 136, in samefile\n"}, "attachments": [{"name": "Failure Screenshot", "source": "3b3cad1d-fd76-47ea-b285-adbe982a6884-attachment.png", "type": "image/png"}], "start": 1736957538285, "stop": 1736957538286}], "parameters": [{"name": "email", "value": "'admin@email.com'"}, {"name": "password", "value": "'admin@123454545'"}], "start": 1736957535922, "stop": 1736957538261, "uuid": "fcdbfd94-42f6-480d-90db-3242fcb1e42e", "testCaseId": "3363a3c2a0dcd6814d51cf393a310bbb", "fullName": "tests.test_login_script.TestLoginScenario#test_login"}